import json
import itertools

variations = json.load(open("variations.json"))

print("""// @generated by gen-root.py. Do not edit.
// Not Material Theme v2.
// Pretty pastels in a wide variety of colours and contrast options.

version 1

@include "gen/harmonized.m.kdl"

@include "modules/extras.m.kdl"
@include "modules/roles.m.kdl"
@include "modules/theme.m.kdl"

name "Maybe Material"
author "github.com/iamawatermelo"

""")


for color, variation in variations.items():
    for (scheme, contrast, background) in itertools.product(
        ["light", "dark"],
        ["standard", "high"],  # "medium",
        ["opaque", "transparent", "blur"]
    ):
        layers = [f'layer "m3-palette-{color}"']
        
        name = variation["names"][0] if scheme == "light" else variation["names"][1]
        variant_name = "Maybe Material"
        
        if background != "opaque":
            # For a better preview experience I'm grouping by contrast
            variant_name += f" [{background.capitalize()}]"
        
        variant_name += f" {name}"
        
        if contrast == "standard":
            layers.append(f'layer "m3-roles-{scheme}-standard"')
            layers.append(f'layer "m3-ext-{scheme}"')
        else:
            variant_name += f" ({contrast.capitalize()})"
            layers.append(f'layer "m3-roles-{scheme}-{contrast}-contrast"')
            layers.append(f'layer "m3-ext-{scheme}-hicontrast"')
        
        layers.append(f'layer "bg-{background}"')
        
        layers.append('layer "theme"')
        
        layers_str = "\n    ".join(layers)

        print(f'variant "{variant_name}" {{')
        print(f'    appearance "{scheme}"')
        print('    ')
        print(f'    {layers_str}')
        print('}\n')