import json

tokens = json.load(open("fixed-tokens.json"))
variations = json.load(open("variations.json"))

print("// @generated by gen-palettes.py. Do not edit.")
print("")
print("version 1")
print("")

common = """    // The main accent colour of the theme.
    token "primary-palette" apply="seed" c=50
    
    // An adjacent accent colour that's a bit different
    token "primary-variant-palette" apply="primary-palette" h="+20"
    
    // A secondary accent colour.
    token "secondary-palette" apply="seed" c=20
    
    // A tertiary, contrasting accent colour.
    token "tertiary-palette" apply="seed" h="+180" c=30
    
    // Used for general UI surfaces like backgrounds and cards.
    token "neutral-palette" apply="seed" c=5
    
    // Used for UI elements that need to be subtly different from the main surface.
    token "neutral-variant-palette" apply="seed" c=10"""

def harmonize(hue: int, seed: int):
    """
    Taken from Material Color Utilities. Harmonize a hue with the seed
    colour so they are more visually pleasing
    """
    distance = float(seed - hue)
    
    if distance > 0:
        shortest_distance = min(distance, distance - 360, key=abs)
    else:
        shortest_distance = min(distance, distance + 360, key=abs)
    
    return int((hue + max(min(shortest_distance * 0.5, 15), -15)) % 360)
    

for name, palette in variations.items():
    root = palette.get("root")
    tertiary = palette.get("tertiary")
    
    print(f'layer "m3-palette-{name}" {{')
    print(f'    token "seed" h={root}')
    print(f'    token "tertiary-seed" h={root}')
    print("")
    print(common)
    print("")
    print("    // Harmonized tokens")
    
    for key, token in tokens.items():
        print(f'    token "{key}" h={harmonize(token["h"], root)} c={token["c"]}  // h={token["h"]}')
    
    print("}")
    print("")